"""add_auth_fields_to_user

Revision ID: 0b132f621fb5
Revises: c5f10b4fbf6a
Create Date: 2025-12-19 22:22:31.559931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b132f621fb5'
down_revision: Union[str, None] = 'c5f10b4fbf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
