"""add last_gmail_sync to users

Revision ID: 438ad87517c7
Revises: 7b82bfab2c70
Create Date: 2026-04-28 16:42:36.137347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438ad87517c7'
down_revision: Union[str, None] = '7b82bfab2c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_gmail_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_gmail_sync')
    # ### end Alembic commands ###
